### ISSUE TITLE
Error when update plugins (Windows 10)

### ISSUE THREAD

**Issue by Eringan** [soutar/hyperterm-summon#34] opened 2017-10-31 11:24 UTC
- [x] I am on the [latest](https://github.com/soutar/hyperterm-summon/releases/latest) hyperterm-summon version
- [x] I have searched the [issues](https://github.com/soutar/hyperterm-summon/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 (1703)
- **Hyper.app version**: 1.4.8
- **hyperterm-summon version**: 2.0.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [here](https://gist.github.com/Eringan/2a159f0518148d74415b4d7f0393940d)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: Nothing

---

### Steps to Reproduce
1. Add hyperterm-summon
2. Update plugins give an error (same error if the plugin is alone)
![hyperterm-summon-error-update](https://user-images.githubusercontent.com/6870883/32219959-358c33f6-be30-11e7-970a-870a845bb79f.png)

### Expected Result
No error and update plugins

### Actual Result
Bugs and no update

---
Thanks for this plugin !
And sorry if my English is poor

**Comment by dcalhoun** [comment] 2017-10-31 12:51
@Eringan thanks for the report. I believe this a duplicate of #31. You experienced this error when upgrading from `2.0.3` (which possessed the bug) to `2.0.4` (which included a fix for the bug).

I'm fairly confident you will not see this error again now that you are on `hyperterm-summon@2.0.4`, but if you do, feel free to post again. Thanks!

**Comment by Eringan** [comment] 2017-10-31 17:23
I followed issue #31 when I had version 2.0.3, I did not have time to open an issue but after the fix 2.0.4, I uninstalled and reinstalled the plugin. This is not the same error, i believe : "at Applyconfig" for # 31, here is "at module.exports". I have version 2.0.4, and still this bug again :s

Thanks to you !

**Comment by dcalhoun** [comment] 2017-10-31 17:39
You are correct! The bug occurs [here](https://github.com/soutar/hyperterm-summon/blob/2.0.4/modules/dispose.js#L12). Thank you for pointing out the exact location. I'll try to publish a fix soon.

**Comment by Eringan** [comment] 2017-10-31 18:13
Ok ! Thank you !

**Closed** 2017-11-01 03:15 UTC
Labels: bug

**Comment by dcalhoun** [comment] 2017-11-01 03:18
@Eringan this should be fixed in `hyperterm-summon@2.0.5`.

**Comment by Eringan** [comment] 2017-11-01 10:59
Cool, everything is ok ! Thank you for the fix !
